// DOCKER
export const dockerFilePg = "version: '3.7'\nservices: \ndb: \nimage: postgres \nrestart: always \nenvironment: \n- POSTGRES_DB=YOUR_PGDATABASE \n- POSTGRES_USER=YOUR_PGUSER \n- POSTGRES_PASSWORD=YOUR_PGPASSWORD \nports: \n- 'YOUR_PGPORT:5432'";

// INSTALL
// ------ express
export const expressInstall = ['express', 'cookie-parser', 'cors', 'cross-env', 'dotenv', 'dotenv-webpack', 'esbuild', 'express-async-errors', 'express-list-endpoints', 'helmet', 'http-errors', 'moment', 'morgan', 'node-fetch@2.6.1', 'winston', 'xss', 'webpack-shell-plugin', 'uuid', 'tslib', 'multer'];
export const expressDevInstall = ['@types/cookie-parser', '@types/cors', '@types/express', '@types/express-list-endpoints', '@types/http-errors', '@types/morgan', '@types/multer', '@types/node-fetch@2.6.2', '@types/request', '@types/uuid', 'copy-webpack-plugin', 'kill-port', 'prettier', 'resolve-tspaths', 'ts-loader', 'ts-node', 'tsconfig-paths', 'tslint', 'typescript', 'webpack', 'webpack-cli', 'webpack-node-externals'];
// ------ react
export const reactInstall = [
    '@emotion/react',
    '@emotion/styled',
    '@fontsource/roboto',
    '@geoapify/geocoder-autocomplete',
    '@geoapify/react-geocoder-autocomplete',
    '@mkyy/mui-search-bar',
    '@mui/icons-material',
    '@mui/lab',
    '@mui/material',
    '@mui/x-data-grid',
    '@mui/x-data-grid-generator',
    '@mui/x-date-pickers',
    'animate.css',
    'chart.js',
    'date-fns',
    'dotenv',
    'i18next',
    'moment',
    'mui-color-input',
    'mui-file-dropzone',
    'mui-file-input',
    'mui-one-time-password-input',
    'mui-tel-input',
    'notistack',
    'react',
    'react-chartjs-2',
    'react-dom',
    'react-error-boundary',
    'react-i18next',
    'react-markdown',
    'react-router-dom',
    'sass',
    'web-vitals',
    '@emotion/react',
    '@emotion/styled',
    '@fontsource/roboto',
    '@geoapify/geocoder-autocomplete',
    '@geoapify/react-geocoder-autocomplete',
    '@mkyy/mui-search-bar',
    '@mui/icons-material',
    '@mui/lab',
    '@mui/material',
    '@mui/x-data-grid',
    '@mui/x-data-grid-generator',
    '@mui/x-date-pickers',
    'animate.css',
    'chart.js',
    'date-fns',
    'dotenv',
    'i18next',
    'moment',
    'mui-color-input',
    'mui-file-dropzone',
    'mui-file-input',
    'mui-one-time-password-input',
    'mui-tel-input',
    'notistack',
    'react',
    'react-chartjs-2',
    'react-dom',
    'react-error-boundary',
    'react-i18next',
    'react-markdown',
    'react-router-dom',
    'sass',
    'web-vitals',
];
export const reactDevInstall = ['@types/node', '@types/react', '@types/react-beautiful-dnd', '@types/react-dom', '@typescript-eslint/eslint-plugin', '@typescript-eslint/parser', '@vitejs/plugin-react', 'cross-env', 'eslint', 'eslint-plugin-react-hooks', 'eslint-plugin-react-refresh', 'prettier', 'serve', 'typescript', 'vite', 'vite-plugin-checker', 'vite-plugin-chunk-split', 'vite-plugin-remove-console', 'vite-plugin-svgr', '@types/node', '@types/react', '@types/react-beautiful-dnd', '@types/react-dom', '@typescript-eslint/eslint-plugin', '@typescript-eslint/parser', '@vitejs/plugin-react', 'cross-env', 'eslint', 'eslint-plugin-react-hooks', 'eslint-plugin-react-refresh', 'prettier', 'serve', 'typescript', 'vite', 'vite-plugin-checker', 'vite-plugin-chunk-split', 'vite-plugin-remove-console', 'vite-plugin-svgr'];
